### ISSUE TITLE
事前学習モデルの配布について

### ISSUE THREAD

**Issue by tonnetonne814** [kyamauchi1023/PL-BERT-ja#1]
突然の連絡失礼いたします。
日本語のPhoneme level BERTということで、個人的に非常に興味が有ります。

事前学習モデルの配布予定などはございますでしょうか。

突然のご連絡申し訳ございませんが、ご返答頂けると幸いです。

**Comment by kyamauchi1023** [comment]
ご連絡ありがとうございます。
事前学習モデルの配布についてですが, 今後学習済みの重みを公開する予定ではあります。
現在事前学習の実験を継続しておりますので, もう少々お待ちいただけますと幸いです。

**Comment by kyamauchi1023** [comment]
先ほど事前学習モデルの重みを公開いたしました。
詳細はREADMEからご確認いただけます。
公開が遅くなってしまい申し訳ありませんでした。
この重みが何かのお役に立てば幸いです。
